// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjJsMkLFCYdoP6T423UruzRRlQa9_SJ20',
    appId: '1:828093578123:web:3fc095f0ecf8bc38784d8e',
    messagingSenderId: '828093578123',
    projectId: 'filmyfun-d52f9',
    authDomain: 'filmyfun-d52f9.firebaseapp.com',
    storageBucket: 'filmyfun-d52f9.firebasestorage.app',
    measurementId: 'G-C0887WVTS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4AWVCYFfn8L0MbUkO6BIqc7HO1GxEnsU',
    appId: '1:828093578123:android:f6dc5915e1994388784d8e',
    messagingSenderId: '828093578123',
    projectId: 'filmyfun-d52f9',
    storageBucket: 'filmyfun-d52f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRnKP7UlxhNzZJGh4Vvr85r-MN_L66N4E',
    appId: '1:828093578123:ios:a006700eac6f6efe784d8e',
    messagingSenderId: '828093578123',
    projectId: 'filmyfun-d52f9',
    storageBucket: 'filmyfun-d52f9.firebasestorage.app',
    iosBundleId: 'com.example.moviebookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRnKP7UlxhNzZJGh4Vvr85r-MN_L66N4E',
    appId: '1:828093578123:ios:a006700eac6f6efe784d8e',
    messagingSenderId: '828093578123',
    projectId: 'filmyfun-d52f9',
    storageBucket: 'filmyfun-d52f9.firebasestorage.app',
    iosBundleId: 'com.example.moviebookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjJsMkLFCYdoP6T423UruzRRlQa9_SJ20',
    appId: '1:828093578123:web:2ffe3fa7d15b2123784d8e',
    messagingSenderId: '828093578123',
    projectId: 'filmyfun-d52f9',
    authDomain: 'filmyfun-d52f9.firebaseapp.com',
    storageBucket: 'filmyfun-d52f9.firebasestorage.app',
    measurementId: 'G-L6256WCPQF',
  );
}
